ARG CERTBOT_VERSION=v5.7.0
FROM certbot/certbot:${CERTBOT_VERSION}

LABEL org.opencontainers.image.title="OneinStack Certbot"
LABEL org.opencontainers.image.source="https://github.com/FeeAI/oneinstack"
