ARG MEMCACHED_VERSION=1.6
FROM memcached:${MEMCACHED_VERSION}-alpine

LABEL org.opencontainers.image.title="OneinStack Memcached"
LABEL org.opencontainers.image.source="https://github.com/FeeAI/oneinstack"

EXPOSE 11211
