ARG PHPMYADMIN_VERSION=5-apache
FROM phpmyadmin:${PHPMYADMIN_VERSION}

LABEL org.opencontainers.image.title="OneinStack phpMyAdmin"
LABEL org.opencontainers.image.source="https://github.com/FeeAI/oneinstack"
