server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;
  root /var/www/html/default;
  index index.php index.html;

  location = /healthz {
    access_log off;
    default_type text/plain;
    return 200 "ok\n";
  }

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/acme;
  }

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    try_files $fastcgi_script_name =404;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass php:9000;
  }

  location ~ /\.(?!well-known).* {
    deny all;
  }
}
